"""
github_service.py — GitHub connection, repo browsing and pull requests.

WHY THIS FILE EXISTS
--------------------
Until now the only GitHub code in SavFlux was `create_pr_via_api` in
`pr_service.py`: one function, one purpose, reached only if `GITHUB_TOKEN` had
been exported into the process environment before launch. There was no way to
connect an account from the product, no way to see which repositories you have,
and no way to look at a pull request after SavFlux opened one. The "GitHub
Action PR review" workflow is a third, separate integration.

So the integration existed as three disconnected pieces that all required the
user to leave the product first. This module makes GitHub a surface *inside*
SavFlux: connect an account, browse what it can see, open a PR, watch its checks.

The branch comparison endpoint uses GitHub's read-only compare API; it never
checks out, changes, or pushes a branch.

TOKEN STORAGE — WHAT IS DELIBERATELY NOT DONE HERE
---------------------------------------------------
The token is written to `data_dir()/github_token`, mode 0600, and is never
returned by any endpoint. `get_token()` prefers `GITHUB_TOKEN` from the
environment so CI and existing deployments keep working untouched; the stored
file is the fallback that makes the product usable without a shell.

The token is NOT encrypted at rest. It is a local dev tool whose whole pitch is
"your code never leaves your machine" — a keyring dependency would make the
$0 quickstart fail on a headless box, and a plaintext file in a directory the
user already trusts (`chroma_data/`) is the same trust decision the rest of the
product already makes. What *is* enforced: the file is 0600, it is excluded
from git, and no response body anywhere in this codebase contains the token.

ERRORS
------
Every failure raises `GitHubError` carrying the HTTP status and GitHub's own
message. Callers get one thing to handle, and the UI can distinguish "your token
is bad" (401) from "that repo does not exist" (404) from "you are rate limited"
(403 + `X-RateLimit-Remaining: 0`) from "GitHub is down" (5xx) — four sentences a
user needs and cannot infer from a single "request failed".
"""

from __future__ import annotations

import asyncio
import base64
import os
import re
from typing import Any, Optional

import httpx

from app.core.paths import data_file

_API = "https://api.github.com"
_TIMEOUT = httpx.Timeout(20.0, connect=8.0)

#: Where a PAT must come from. Generated by GitHub when the user creates one.
#: Used to tell the user *which* permission is missing instead of "401".
SCOPES_HINT = "repo, read:user"


class GitHubError(RuntimeError):
    """A GitHub call that did not succeed, with enough detail to act on."""

    def __init__(self, message: str, status: int = 0, kind: str = "error"):
        super().__init__(message)
        self.status = status
        self.kind = kind  # auth | not_found | rate_limit | network | error | validation


# ── Token storage ────────────────────────────────────────────────────────────

def _token_path():
    return data_file("github_token")


def store_token(token: str) -> None:
    """Persist a PAT to disk with owner-only permissions.

    The chmod is done explicitly *and* after the write, because the file is
    created with the process umask — on a default umask of 022 the first write
    is world-readable for the (very short) window before the chmod lands.
    """
    path = _token_path()
    path.write_text(token.strip(), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        # A filesystem without POSIX modes (Windows, some network mounts) is not
        # a reason to refuse to connect — the warning is the user's problem to
        # notice, not a 500 on a working integration.
        pass


def clear_token() -> bool:
    path = _token_path()
    if not path.exists():
        return False
    path.unlink()
    return True


def get_token() -> str:
    """The token to authenticate with, or "" when GitHub is not connected.

    The token the user connected **in the app** wins over `GITHUB_TOKEN` from
    the environment, and the reason is not cosmetic: a machine very often
    already exports a `GITHUB_TOKEN` for something else entirely — CI, a deploy
    script, another tool on the same box. With environment-first, the product
    would show *that* account's repositories in the repo picker and open pull
    requests as a stranger, with nothing on screen to explain it. The account a
    person connected on purpose is the one they mean.

    The environment remains the fallback, so a headless deployment that never
    touches the UI keeps working exactly as it did.
    """
    try:
        saved = _token_path().read_text(encoding="utf-8").strip()
        if saved:
            return saved
    except OSError:
        pass
    return os.getenv("GITHUB_TOKEN", "").strip()


def is_connected() -> bool:
    return bool(get_token())


# ── HTTP plumbing ────────────────────────────────────────────────────────────

def _headers(token: str) -> dict:
    return {
        **({"Authorization": f"Bearer {token}"} if token else {}),
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "SavFlux",
    }


def _classify(status: int, remaining: str | None) -> tuple[str, str]:
    if status in (401,):
        return "auth", "GitHub rejected the token. Create a new one with the 'repo' scope and reconnect."
    if status == 429 or (status == 403 and remaining == "0"):
        return "rate_limit", "GitHub's API rate limit was reached. Wait for it to reset before retrying."
    if status == 403:
        return "auth", "The token is missing a permission this request needs (usually 'repo' for private repositories)."
    if status == 404:
        return "not_found", "Not found — the repository does not exist, or the token cannot see it."
    if status == 422:
        return "validation", "GitHub rejected the request as invalid."
    if status >= 500:
        return "error", f"GitHub is having trouble (HTTP {status}). Try again shortly."
    return "error", f"GitHub returned HTTP {status}."


async def _request(
    method: str,
    path: str,
    *,
    token: Optional[str] = None,
    params: dict | None = None,
    json_body: dict | None = None,
    allow_anonymous: bool = False,
) -> Any:
    tok = token if token is not None else get_token()
    if not tok and not (allow_anonymous and method == "GET"):
        raise GitHubError("GitHub is not connected.", status=0, kind="auth")
    url = path if path.startswith("http") else f"{_API}{path}"
    try:
        async with httpx.AsyncClient(timeout=_TIMEOUT, follow_redirects=True) as client:
            resp = await client.request(
                method, url, headers=_headers(tok), params=params, json=json_body
            )
    except httpx.HTTPError as exc:
        # DNS, TLS, connect timeout — "GitHub could not be reached" is a
        # different sentence from "GitHub said no", and the UI shows both.
        raise GitHubError(
            f"Could not reach api.github.com ({exc.__class__.__name__}).", kind="network"
        ) from exc

    if resp.status_code >= 400:
        kind, message = _classify(resp.status_code, resp.headers.get("X-RateLimit-Remaining"))
        # GitHub puts the useful sentence in `message`; prefer it.
        try:
            body = resp.json()
            if isinstance(body, dict) and body.get("message"):
                message = f"{body['message']}"
        except Exception:
            pass
        raise GitHubError(message, status=resp.status_code, kind=kind)

    if resp.status_code == 204 or not resp.content:
        return {}
    return resp.json()


# ── Shaping ──────────────────────────────────────────────────────────────────

def _size_gb(n: int | None) -> float | None:
    return round(n / 1024**3, 2) if isinstance(n, int) else None


def shape_permissions(raw: dict) -> dict:
    """
    What the connected account may actually do to this repository.

    WHY THIS IS ON EVERY REPO, NOT JUST THE ONE YOU OPENED
    ------------------------------------------------------
    `permissions` is GitHub's own answer to "can this token push here", computed
    from the token's fine-grained grants, the collaborator's role, and branch
    protection. It is the only signal that is true by construction — asking the
    user which scope they picked means trusting a UI dropdown, and a dropdown
    that is wrong only fails later, at push time, on someone else's repository.

    An unauthenticated request has no `permissions` object at all, which is the
    point: a public repository read with no token reports `push: false`, and the
    product can say "connect GitHub to open a pull request" rather than offering
    a button that will 401. Absence is read as "cannot", never as "can".
    """
    perms = raw.get("permissions") or {}
    return {
        "admin": bool(perms.get("admin")),
        "push": bool(perms.get("push")),
        "pull": bool(perms.get("pull")),
    }


def shape_repo(raw: dict) -> dict:
    return {
        "full_name": raw.get("full_name"),
        "name": raw.get("name"),
        "owner": (raw.get("owner") or {}).get("login"),
        "private": bool(raw.get("private")),
        "description": raw.get("description"),
        "default_branch": raw.get("default_branch"),
        "language": raw.get("language"),
        "stars": raw.get("stargazers_count", 0),
        "forks": raw.get("forks_count", 0),
        "open_issues": raw.get("open_issues_count", 0),
        "size_kb": raw.get("size", 0),
        "pushed_at": raw.get("pushed_at"),
        "clone_url": raw.get("clone_url"),
        "html_url": raw.get("html_url"),
        "archived": bool(raw.get("archived")),
        "permissions": shape_permissions(raw),
    }


def shape_pull(raw: dict) -> dict:
    user = raw.get("user") or {}
    head = raw.get("head") or {}
    base = raw.get("base") or {}
    return {
        "number": raw.get("number"),
        "title": raw.get("title"),
        "state": raw.get("state"),
        "draft": bool(raw.get("draft")),
        "author": user.get("login"),
        "author_avatar": user.get("avatar_url"),
        "head": head.get("ref"),
        "base": base.get("ref"),
        "created_at": raw.get("created_at"),
        "updated_at": raw.get("updated_at"),
        "merged": bool(raw.get("merged_at")),
        "html_url": raw.get("html_url"),
        "additions": raw.get("additions"),
        "deletions": raw.get("deletions"),
        "changed_files": raw.get("changed_files"),
        "labels": [l.get("name") for l in (raw.get("labels") or []) if l.get("name")],
        "body": raw.get("body") or "",
    }


# ── Public surface ───────────────────────────────────────────────────────────

async def get_viewer(token: str) -> dict:
    """Validate a token and return the account it belongs to."""
    data = await _request("GET", "/user", token=token)
    return {
        "login": data.get("login"),
        "name": data.get("name"),
        "avatar_url": data.get("avatar_url"),
        "html_url": data.get("html_url"),
        "type": data.get("type"),
    }


async def status() -> dict:
    """Connection state, for the top bar.

    A stored token is not proof of a working integration: it can be expired,
    revoked, or from an account with no repo access. So this calls `/user`
    rather than reporting what is on disk, and degrades to `connected: true,
    valid: false` with the reason — a header that says "connected" while every
    action 401s is worse than one that says what is wrong.
    """
    if not is_connected():
        return {
            "connected": False,
            "valid": False,
            "source": None,
            "user": None,
            "message": "Connect a GitHub account to browse repositories and open pull requests.",
        }
    try:
        saved = _token_path().read_text(encoding="utf-8").strip()
    except OSError:
        saved = ""
    source = "app" if saved else "env"
    try:
        viewer = await get_viewer(get_token())
        return {
            "connected": True, "valid": True, "source": source,
            "user": viewer, "message": None,
        }
    except GitHubError as exc:
        return {
            "connected": True, "valid": False, "source": source, "user": None,
            "message": str(exc), "kind": exc.kind,
        }


_viewer_cache: dict[str, Any] = {"login": None, "token": None}


async def viewer_login() -> str:
    """The authenticated login, memoised for the life of the process.

    Needed because the repository *search* endpoint has no "mine" filter — the
    query has to name a user — so a search costs one extra `/user` call the
    first time and nothing after that. The cache is keyed by token, so
    reconnecting as a different account cannot serve the previous one's login.
    """
    token = get_token()
    if _viewer_cache["token"] == token and _viewer_cache["login"]:
        return _viewer_cache["login"]
    login = (await get_viewer(token)).get("login") or ""
    _viewer_cache.update({"login": login, "token": token})
    return login


async def list_repos(
    *, per_page: int = 50, page: int = 1, sort: str = "pushed", query: str = ""
) -> list[dict]:
    """Repositories the connected account can see, newest activity first.

    `query` is a server-side search (`q=`) rather than a client-side filter: the
    account's repository list is frequently longer than one page, and filtering
    the first page locally means a search silently misses everything the user
    has not scrolled to. GitHub's search API cannot express "repositories this
    token can see" directly, so the query is scoped to the viewer's login —
    which is also why a token for a machine user searches that user's repos and
    not an organisation's.
    """
    per_page = max(1, min(per_page, 100))
    if query:
        login = await viewer_login()
        scope = f"user:{login}" if login else ""
        raw = await _request(
            "GET", "/search/repositories",
            params={
                "q": f"{query} in:name,description {scope}".strip(),
                # The search endpoint offers `updated`, not `pushed`; these are
                # different fields and using the wrong one silently sorts by the
                # repository's last metadata edit instead of its last commit.
                "sort": "updated", "order": "desc",
                "per_page": per_page, "page": page,
            },
        )
        return [shape_repo(r) for r in (raw.get("items") or [])]
    raw = await _request(
        "GET", f"/user/repos",
        params={"per_page": per_page, "page": page, "sort": sort,
                "affiliation": "owner,collaborator,organization_member"},
    )
    return [shape_repo(r) for r in raw]


async def get_repo(slug: str) -> dict:
    raw = await _request("GET", f"/repos/{slug}", allow_anonymous=True)
    out = shape_repo(raw)
    # `shape_repo` already carries permissions, which come from the
    # authenticated user's view rather than the public repo object — they are
    # what decides whether a pull request can be opened at all. `GET /repos/{slug}`
    # additionally reports open issues that include pull requests, so use that
    # count here rather than the one in the list response.
    out["open_pr_count"] = raw.get("open_issues_count", 0)
    return out


def can_write(repo: dict | None) -> bool:
    """
    May this account push to `repo`? One definition, so the review panel, the
    agent's `create_pr` tool and the repository list cannot each answer it
    differently — a button that appears where a push will fail is worse than no
    button, because it costs the user a round trip to find out.
    """
    if not repo:
        return False
    return bool((repo.get("permissions") or {}).get("push"))


async def list_branches(slug: str, *, per_page: int = 100, page: int = 1) -> list[dict]:
    """Read remote branches; public repos do not require a GitHub connection."""
    raw = await _request(
        "GET", f"/repos/{slug}/branches",
        params={"per_page": max(1, min(per_page, 100)), "page": max(1, page)},
        allow_anonymous=True,
    )
    return [
        {
            "name": b.get("name"),
            "protected": bool((b.get("protected") or False)),
            "sha": ((b.get("commit") or {}).get("sha") or "")[:8],
        }
        for b in raw
    ]


async def compare_branches(slug: str, base: str, head: str) -> dict:
    """Read-only comparison of two GitHub branch refs.

    GitHub's compare API defines the direction as `base...head`: ahead/behind
    counts and file patches therefore stay attached to the refs the user chose.
    Branch names are URL-encoded as one path segment so refs such as
    `feature/parser-v2` cannot accidentally alter the endpoint path.
    """
    from urllib.parse import quote

    base_ref = quote(base, safe="")
    head_ref = quote(head, safe="")
    raw = await _request(
        "GET",
        f"/repos/{slug}/compare/{base_ref}...{head_ref}",
        params={"per_page": 100},
        allow_anonymous=True,
    )
    if not isinstance(raw, dict):
        raise GitHubError("GitHub returned an invalid branch comparison.", kind="error")

    files = raw.get("files") or []
    shaped_files: list[dict] = []
    patch_budget = 500_000
    files_truncated = len(files) > 100
    for item in files[:100]:
        patch = item.get("patch")
        patch_truncated = False
        if isinstance(patch, str):
            allowed = min(20_000, patch_budget)
            if len(patch) > allowed:
                patch = patch[:allowed]
                patch_truncated = True
            patch_budget -= len(patch)
        else:
            # GitHub omits a patch for binary or very large files.
            patch = None
        shaped_files.append({
            "filename": str(item.get("filename") or "")[:500],
            "previous_filename": item.get("previous_filename"),
            "status": str(item.get("status") or "modified"),
            "additions": int(item.get("additions") or 0),
            "deletions": int(item.get("deletions") or 0),
            "changes": int(item.get("changes") or 0),
            "patch": patch,
            "patch_truncated": patch_truncated,
        })

    raw_commits = raw.get("commits") or []
    commits = []
    for item in raw_commits[:50]:
        commit = item.get("commit") or {}
        author = commit.get("author") or {}
        message = str(commit.get("message") or "").splitlines()[0][:180]
        commits.append({
            "sha": str(item.get("sha") or "")[:8],
            "message": message,
            "author": author.get("name"),
            "date": author.get("date"),
            "url": item.get("html_url"),
        })

    return {
        "repo": slug,
        "base": base,
        "head": head,
        "status": str(raw.get("status") or "unknown"),
        "ahead_by": int(raw.get("ahead_by") or 0),
        "behind_by": int(raw.get("behind_by") or 0),
        "total_commits": int(raw.get("total_commits") or len(commits)),
        "changed_files": int(raw.get("total_files") or len(files)),
        "files": shaped_files,
        "files_truncated": files_truncated,
        "commits": commits,
        "commits_truncated": len(raw_commits) > len(commits),
    }


async def list_pulls(slug: str, *, state: str = "open", per_page: int = 30) -> list[dict]:
    raw = await _request(
        "GET", f"/repos/{slug}/pulls",
        params={"state": state, "per_page": max(1, min(per_page, 100)), "sort": "updated", "direction": "desc"},
    )
    return [shape_pull(p) for p in raw]


async def get_pull(slug: str, number: int) -> dict:
    """One pull request with its files and check runs.

    The three are three requests, so they are fetched together. `checks` is
    best-effort: a repo with Actions disabled 404s on the check-runs endpoint,
    and a pull request whose CI is simply not configured is a normal state, not
    an error worth failing the whole panel over.
    """
    pull, files, checks = await asyncio.gather(
        _request("GET", f"/repos/{slug}/pulls/{number}"),
        _request("GET", f"/repos/{slug}/pulls/{number}/files", params={"per_page": 100}),
        _request("GET", f"/repos/{slug}/commits/{number}/check-runs"),
        return_exceptions=True,
    )
    if isinstance(pull, Exception):
        raise pull
    out = shape_pull(pull)
    out["mergeable"] = pull.get("mergeable")
    out["mergeable_state"] = pull.get("mergeable_state")
    out["comments"] = pull.get("comments", 0)
    out["review_comments"] = pull.get("review_comments", 0)
    out["commits"] = pull.get("commits", 0)
    out["files"] = [
        {
            "filename": f.get("filename"),
            "status": f.get("status"),
            "additions": f.get("additions"),
            "deletions": f.get("deletions"),
            "patch": f.get("patch"),
        }
        for f in (files if isinstance(files, list) else [])
    ]
    if isinstance(checks, dict):
        out["checks"] = [
            {
                "name": (run.get("name")),
                "status": run.get("status"),
                "conclusion": run.get("conclusion"),
                "url": run.get("html_url"),
            }
            for run in (checks.get("check_runs") or [])
        ]
    else:
        out["checks"] = []
    return out


async def create_pull(slug: str, *, title: str, head: str, base: str, body: str = "") -> dict:
    raw = await _request(
        "POST", f"/repos/{slug}/pulls",
        json_body={"title": title, "head": head, "base": base, "body": body},
    )
    return shape_pull(raw)


def auth_clone_kwargs() -> dict:
    """Extra kwargs for `git.Repo.clone_from` that authenticate a private repo.

    The credential is handed to git through the `GIT_CONFIG_*` environment
    protocol rather than being embedded in the clone URL. A URL-embedded token
    (`https://x-access-token:ghp_…@`) lands in `.git/config` of the clone, in
    `git remote -v` output, and in every error message that quotes the remote —
    which is how a token ends up pasted into a bug report. Here the clone's
    `.git/config` contains nothing but the remote URL.

    It is *not* passed as GitPython's `multi_options`, which looks equivalent
    (`-c http.…extraheader=…`) but is not:

    * GitPython 3.1.36+ refuses `multi_options` unless `allow_unsafe_options`
      is passed, because `-c` can rewrite arbitrary git config.
    * More seriously, GitPython splits each `multi_options` entry on
      whitespace before handing it to git. The header value is
      `AUTHORIZATION: basic <base64>`, and the space after the colon made git
      receive three arguments where it expected one — `fatal: Too many
      arguments`, exit code 129. The raw `git` binary handles the same
      argument correctly, which is exactly what makes this hard to spot.

    `GIT_CONFIG_COUNT`/`GIT_CONFIG_KEY_n`/`GIT_CONFIG_VALUE_n` (git 2.31+) has
    neither problem: the value is passed as an opaque environment entry, it
    never reaches `.git/config`, and nothing has to be marked unsafe.

    With no token connected this returns `{}` and the clone is fully
    unauthenticated, which is the public-repository path.
    """
    token = get_token()
    if not token:
        return {}
    basic = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    return {
        "env": {
            **os.environ,
            "GIT_CONFIG_COUNT": "1",
            "GIT_CONFIG_KEY_0": "http.https://github.com/.extraheader",
            "GIT_CONFIG_VALUE_0": f"AUTHORIZATION: basic {basic}",
        }
    }


__all__ = [
    "GitHubError", "SCOPES_HINT", "is_connected", "get_token", "store_token",
    "clear_token", "status", "get_viewer", "list_repos", "get_repo",
    "list_branches", "compare_branches", "list_pulls", "get_pull", "create_pull",
    "auth_clone_kwargs", "parse_slug", "can_write", "shape_repo",
    "shape_permissions",
]

_SLUG_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


def parse_slug(slug: str) -> str:
    """Normalize `owner/name` or a github.com URL to `owner/name`."""
    from app.services.pr_service import parse_repo_ref  # reuse the validation

    return parse_repo_ref(slug)
